'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useSession} from 'next-auth/react';
import {useRouter} from 'next/navigation';
type Item={slug:string;title:string;price:string;amountMinor:number;market:'US'|'UK'};
export default function Checkout(){
 const {status}=useSession(); const router=useRouter(); const [items,setItems]=useState<Item[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem('diginanba-cart')||'[]'))}catch{}},[]);
 const market=items[0]?.market||'US'; const total=items.reduce((s,x)=>s+x.amountMinor,0); const fmt=new Intl.NumberFormat(market==='US'?'en-US':'en-GB',{style:'currency',currency:market==='US'?'USD':'GBP'});
 async function pay(){setError(''); if(status!=='authenticated'){router.push('/login?callbackUrl=/checkout');return;} setBusy(true); try{const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({market,items:items.map(x=>({slug:x.slug,quantity:1}))})}); const d=await r.json(); if(!r.ok)throw new Error(d.error||'Checkout failed'); if(d.demo){localStorage.removeItem('diginanba-cart'); router.push(`/order-success?orderId=${d.orderId}&mode=demo`); return;} throw new Error('Production checkout is not activated in this pre-launch build.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="wrap checkout-page"><div className="sectionhead"><div><div className="eyebrow">Pre-launch checkout</div><h1>Complete your order</h1></div><Link className="btn" href="/cart">← Cart</Link></div>{!items.length?<div className="panel"><h2>Your cart is empty</h2><Link className="btn primary" href="/explore">Explore products</Link></div>:<div className="checkout-grid"><div className="panel"><h2>Order summary</h2>{items.map((x,i)=><div className="cart-row" key={x.slug+i}><span>{x.title}</span><b>{x.price}</b></div>)}<div className="total-row"><span>Total</span><strong>{fmt.format(total/100)}</strong></div></div><div className="panel"><h2>Payment</h2><p className="muted">Real-money payments are disabled. This development build records a pending order only and does not mark it as paid.</p>{error&&<p className="error">{error}</p>}<button className="btn primary wide" disabled={busy} onClick={pay}>{busy?'Creating order…':status==='authenticated'?'Create development order':'Sign in to continue'}</button><p className="small muted">Production checkout will be enabled only after provider onboarding, testing, webhook verification, and owner approval.</p></div></div>}</main>}
