'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
export default function Settings(){const [market,setMarket]=useState('US');const [language,setLanguage]=useState('English');const [email,setEmail]=useState(true);const [saved,setSaved]=useState(false);
useEffect(()=>{setMarket(localStorage.getItem('diginanba-market')||'US');setLanguage(localStorage.getItem('diginanba-language')||'English');setEmail(localStorage.getItem('diginanba-email-updates')!=='false')},[]);
function save(){localStorage.setItem('diginanba-market',market);localStorage.setItem('diginanba-language',language);localStorage.setItem('diginanba-email-updates',String(email));setSaved(true);setTimeout(()=>setSaved(false),1800)}
return <main className="wrap"><Link href="/account" className="muted">← Account</Link><div className="page-head"><div><div className="eyebrow">ACCOUNT SETTINGS</div><h1>Preferences</h1><p className="muted">Control your market, language and communication preferences.</p></div></div><div className="settings-grid">
<section className="panel"><h2>Market & currency</h2><p className="muted">Your storefront market controls prices and localized editions.</p><label className="setting-row">Market<select value={market} onChange={e=>setMarket(e.target.value)}><option value="US">United States · USD</option><option value="UK">United Kingdom · GBP</option></select></label></section>
<section className="panel"><h2>Language</h2><label className="setting-row">Preferred language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>Spanish</option><option>French</option><option>German</option><option>Hindi</option><option>Tamil</option></select></label><p className="muted">More country and local-language editions will be added to the global marketplace.</p></section>
<section className="panel"><h2>Notifications</h2><label className="toggle-row"><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/> Product updates, offers and new releases</label></section>
<section className="panel"><h2>Privacy & security</h2><p className="muted">Your account area is protected by authentication. Password and security controls will expand as account infrastructure grows.</p><Link href="/account" className="btn">Account overview</Link></section>
</div><div className="settings-actions"><button className="btn primary" onClick={save}>{saved?'Saved ✓':'Save preferences'}</button></div></main>